"""company inbox

Revision ID: 9a414722cbc4
Revises: d1c3dd8a3c22
Create Date: 2026-10-07 21:18:18.854823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a414722cbc4'
down_revision: Union[str, None] = 'd1c3dd8a3c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inbox_token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('inbox_allowed', sa.Text(), server_default='', nullable=False))
        batch_op.create_index(batch_op.f('ix_companies_inbox_token'), ['inbox_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_inbox_token'))
        batch_op.drop_column('inbox_allowed')
        batch_op.drop_column('inbox_token')

    # ### end Alembic commands ###
