"""candidate profiles

Revision ID: d1c3dd8a3c22
Revises: 8a161f444b4f
Create Date: 2026-10-07 14:41:59.674175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c3dd8a3c22'
down_revision: Union[str, None] = '8a161f444b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('years', sa.Float(), nullable=False),
    sa.Column('job_family', sa.String(length=40), nullable=True),
    sa.Column('titles', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('inferred_skills', sa.JSON(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_profiles_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_profiles_document_id'), ['document_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_document_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_company_id'))

    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
